routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('welcome');
});

Route::get('/setup/user', 'VisitorController@setupUser')->name('setupUser');
Route::post('/setup/user', 'VisitorController@register')->name('visitor.register');
Route::post('/setup/logo', 'VisitorController@uploadLogo')->name('app.logo');
Route::post('/setup/name', 'VisitorController@saveAppName')->name('app.name');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::group([ 'middleware' => [ 'auth'] ], function(){

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/member/register', 'MemberController@create')->name('member.register.form');
    Route::post('/member/register', 'MemberController@store')->name('member.register');
    Route::get('/members/all', 'MemberController@index')->name('members.all');
    Route::get('/member/profile/{id}', 'MemberController@show')->name('member.profile');
    Route::get('/member/edit/{id}', 'MemberController@modify')->name('member.edit');
    Route::post('/member/delete/{id}', 'MemberController@destroy')->name('member.delete');
    Route::post('/member/delete', 'MemberController@delete')->name('member.delete.multi');
    Route::post('/member/upgrade', 'MemberController@upgrade')->name('member.upgrade');
    Route::post('/member/upload/img', 'MemberController@uploadImg')->name('member.upload.img');
    Route::post('/member/update', 'MemberController@updateMember')->name('member.update');
    Route::get('/member/analysis', 'MemberController@memberAnalysis')->name('member.analysis');
    Route::get('/member/stats', 'MemberController@memberRegStats')->name('member.reg.stats');
    Route::get('/member/attendance/{id}', 'MemberController@attendance')->name('member.attendance');

    Route::get('/branches', 'BranchController@index')->name('branches');
    Route::get('/branches/{id}/destroy', 'BranchController@destroy')->name('branch.destroy');
    Route::get('/branches/register', 'BranchController@registerForm')->name('branch.register.form');
    Route::post('/branches/register', 'BranchController@register')->name('branch.register');
    Route::post('/branches/update', 'BranchController@updateBranch')->name('branch.update');
    Route::post('/branches/delete', 'BranchController@delete')->name('branch.delete.multi');
    Route::get('/branch/invoice', 'BranchController@invoice')->name('branch.invoice');
    // depre
    Route::get('/old/branches/head_office_options', 'BranchController@ho')->name('branch.ho');
    Route::post('/old/branches/head_office_options', 'BranchController@ho_up')->name('branch.ho.up');
    // depre

    Route::get('/attendance', 'AttendanceController@mark')->name('attendance');
    Route::post('/attendance/mark', 'AttendanceController@mark_it')->name('attendance.mark');
    // Route::post('/attendance', 'AttendanceController@store')->name('attendance.selectDate');
    Route::post('/attendance/submit', 'AttendanceController@store')->name('attendance.submit');
    //Route::post('/attendance/mark/submit', 'AttendanceController@store')->name('attendance.mark.submit');
    Route::get('/attendance/analysis', 'AttendanceController@analysis')->name('attendance.analysis');
    Route::get('/attendance/view', 'AttendanceController@view')->name('attendance.view.form');
    //function () {        return view('attendance.view');});
    Route::post('/attendance/view', 'AttendanceController@show')->name('attendance.view');
    Route::get('/attendance/view/{date}', 'AttendanceController@show')->name('attendance.view.custom');
    Route::get('/attendance/stats', 'AttendanceController@attendanceStats')->name('attendance.stats');

    // collection
    Route::get('/collection/offering', 'CollectionController@index')->name('collection.offering');
    Route::post('/collection/save', 'CollectionController@store')->name('collection.save');
    Route::post('/collection/member', 'CollectionController@member')->name('collection.save.member');
    Route::get('/collection/report', 'CollectionController@report')->name('collection.report');
    Route::get('/collection/analysis', 'CollectionController@analysis')->name('collection.analysis');
    Route::get('/collection/history', 'CollectionController@history')->name('collection.history');
    Route::get('/collection/stats', 'CollectionController@collectionStats')->name('collection.stats');

    // calendar
    Route::get('/calendar', 'EventController@index')->name('calendar');
    Route::post('/calendar', 'EventController@store')->name('calendar.update');
    Route::get('/calendar/{id}/delete', 'EventController@destroy')->name('calendar.delete');
    Route::get('/get-relative/{search_term}', 'MemberController@getRelative')->name('relative');

    Route::get('/gallery', 'HomeController@gallery')->name('gallery');

    Route::get('/groups', 'GroupController@index')->name('groups');
    Route::post('/group/create', 'GroupController@store')->name('group.create');
    Route::post('group/members', 'GroupController@members')->name('group.members');
    Route::get('group/default/{name}', 'GroupController@defaultView')->name('group.default.view');
    Route::get('/group/{id}', 'GroupController@show')->name('group.view');
    Route::post('group/{id}/add', 'GroupController@add_member')->name('group.add.member');
    Route::get('group/{id}/delete', 'GroupController@destroy')->name('group.delete');
    Route::get('group/{id}/{group_id}/remove', 'GroupController@remove_member')->name('group.remove.member');


    Route::get('/messaging/email', 'MessagingController@indexEmail')->name('email');
    Route::get('/messaging/sms', 'MessagingController@indexSMS')->name('sms');
    Route::post('/messaging/email/send', 'MessagingController@sendEmail')->name('sendMail');
    Route::post('/messaging/sms/send', 'MessagingController@sendSMS')->name('sendSMS');
    Route::get('/inbox', 'MessagingController@inbox')->name('inbox');
    Route::post('/inbox/message/send', 'MessagingController@sendMessage')->name('sendMessage');
    Route::get('/inbox/conversation/{from?}/{to?}', 'MessagingController@getMsg')->name('conversation');
    Route::post('/inbox/reply', 'MessagingController@reply')->name('reply');
    Route::get('/inbox/inbox', 'MessagingController@get_inbox')->name('inbox.inbox');
    Route::get('/inbox/users', 'MessagingController@get_users')->name('inbox.users');
    Route::get('/inbox/demo', 'MessagingController@demo')->name('inbox.demo');

    Route::get('/report/membership', 'ReportController@membership')->name('report.membership');
    Route::get('/report/membership/all', 'ReportController@allMembership')->name('report.membership.all');
    Route::get('/report/collections', 'ReportController@collections')->name('report.collections');
    Route::get('/report/collections/all', 'ReportController@allCollections')->name('report.collections.all');
    Route::get('/report/attendance', 'ReportController@attendance')->name('report.attendance');
    Route::get('/report/attendance/all', 'ReportController@allAttendance')->name('report.attendance.all');
    //New route from kenny
     Route::get('/notification', 'EventController@news')->name('notification');
    Route::post('/readmore', 'EventController@readmore')->name('readmore');
    Route::post('/notification/announcement', 'EventController@add')->name('calendar.announcement');
    Route::get('/ticket', 'MessagingController@indexticket')->name('ticket');
    Route::post('/ticket/email/ticket', 'MessagingController@sendTicket')->name('sendTicket');

    // OPTIONS
    Route::get('/options/get', 'OptionController@getOption')->name('option.get');
    Route::get('/options/branch/get', 'OptionController@getBranchOption')->name('option.branch.get');
    Route::post('/options/branch/put', 'OptionController@putBranchOption')->name('option.branch.post');
    Route::get('/branches/options', 'BranchController@options')->name('branch.options');
    Route::post('/branches/options', 'OptionController@optionsPost')->name('branch.optionsPost');
    Route::get('/branches/unsettled', 'OptionController@getUnsettled')->name('branch.unsettled');
    // TOOLS
    Route::get('/branches/tools', 'BranchController@tools')->name('branch.tools');
    Route::post('/branches/tools', 'OptionController@toolsPost')->name('branch.toolsPost');
    Route::get('/branches/tools/collection-type', 'OptionController@collectionTypeGet')->name('collection.type');
    Route::get('/branches/tools/service-type', 'OptionController@serviceTypeGet')->name('service.type');
    Route::post('/branches/tools/collection-type/delete', 'OptionController@deletecollectionType')->name('delete.collection.type');
    Route::post('/branches/tools/service-type/delete', 'OptionController@deleteServiceType')->name('delete.service.type');
    Route::post('/branches/tools/service-type/update', 'OptionController@updateServiceType')->name('update.service.type');
    Route::post('/branches/tools/collection-type/update', 'OptionController@updateCollectionType')->name('update.collection.type');
    // Route::post('/branches/tools', 'OptionController@toolsPost')->name('branch.toolsPost');
    // PAYMENT
    Route::resource('/payments', 'PaymentController');
    Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');
    Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
    Route::get('/payment/status', 'PaymentController@status');

    // test
    Route::get('/currencies/get', 'OptionController@getCurrencies')->name('option.currencies');

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\User;
use Illuminate\Http\Request;
use DB;
use App\H_O_Options;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Input;
use DataTables;
use Paystack;
use Dcblogdev\Countries\Facades\Countries;

class BranchController extends Controller
{
    private $user;

    public function __construct()
    {
      $this->user = \Auth::user();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $user = \Auth::user();
      if(!$user->isAdmin()){
        return redirect()->route('dashboard');
      }
      //$members = Member::all();
      if ($request->draw) {
        return DataTables::of(User::all())->make(true);
      } else {
        return view('branch.all');
      }
    }

    public function users(){
      return DataTables::of(User::all())->make(true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
        $id = $request->id;
        $user = \Auth::user();
        DB::table('users')->where('id', '=', $id)->delete();
         return response()->json(['success' => true,]);
    }

    public function registerForm()
    {
        //
        $user = \Auth::user();
        $currencies = Countries::all();

        return ($user->isAdmin()) ? view('branch.register', compact('currencies')) : redirect()->route('dashboard');
    }



    public function register(Request $request)
    {
      $data = [];
      $data['branchname'] = $request->branchname;
      $data['branchcode'] = $request->branchcode;
      $data['address'] = $request->address;
      $data['email'] = $request->email;
      $data['country'] = $request->country;
      $data['state'] = $request->state;
      $data['city'] = $request->city;
      if (!User::first()) {
        $data['isadmin'] = true;
      }
      $data['currency'] = $request->currency;
      $data['password'] = $request->password;
      $data['password_confirmation'] = $request->password_confirmation;

      $validate = self::validator($data);
      if($validate->fails()){
        return redirect()->back()->withErrors($validate)->withInput();
      }
      $creation = self::creator($data);
      //
      $success = 'Successfully Registered';
      return redirect()->back()->with('status', $success);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'branchname' => 'bail|required|string|max:255',
            'branchcode' => 'required|string|max:255|unique:users',
            'address' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
            'country' => 'required|string|max:255',
            'state' =>  'required|string|max:255',
            'city' => 'required|string|max:255',
            'currency' => 'required',
        ]);
    }

    protected function creator(array $data)
    {
      $branch = User::create([
        'branchname' => $data['branchname'],
        'branchcode' => $data['branchcode'],
        'address' => $data['address'],
        'email' => $data['email'],
        'isadmin' => isset($data['isadmin']) ? $data['isadmin'] : 'false',
        'password' => Hash::make($data['password']),
        'country' => $data['country'],
        'state' => $data['state'],
        'city' => $data['city'],
        'currency' => $data['currency'],
      ]);

      if (!$branch) {
        return $branch;
      }

    }

    public function ho(Request $request){
      $user = \Auth::user();
      $options = \App\head_office_options::all();

      return view('branch.ho', ['options' => $options]);
    }

    public function delete(Request $request){
      $failed = 0;
      $text = "All selected branches were deleted successfully";
      foreach ($request->id as $key => $value) {
        $branch = User::whereId($value)->first();
        if($branch){
          $branch->delete();
        } else {
          $failed++;
          $text = "$failed Operations could not be performed";
        }
      }
      return response()->json(['status' => true, 'text' => $text]);
    }

    public function tools(){
      return view('branch.tools');
    }

    public function options(){
      return view('branch.options');
    }

    public function updateBranch(Request $request){
      $branch = User::whereId($request->id)->first();
      // dd($request);
      if($branch) {
        $errors = [];
        $fields = (array)$request->request;//->parameters;//->ParameterBag->parameters;
        $fields = $fields["\x00*\x00parameters"];
        foreach ($fields as $key => $value) {
          if ($key != 'id' && $key != '_token' && $key != 'action') {
              $branch->$key = $request->$key;
          }
        }
        try {
          $branch->save();
        } catch (\Exception $e) {
          array_push($errors, $e);
          // dd($e);
          return response()->json(['status' => false, 'text' => $e->errorInfo[2]]);
        }
      }
      else {return response()->json(['status' => false, 'text' => "Branch does not exist"]);}
      return response()->json(['status' => true, 'text' => "Branch has been updated!"]);
    }

    public function invoice(Request $request){
      $user = \Auth::user();
      // get due savings
      $dueSavings = \App\CollectionCommission::dueSavings($user);
      // if nothing found for the branch
      // redirect back withErrors
      if(!isset($dueSavings[$user->id])) return back()->withErrors(['message' => 'Nothing to pay']);
      // get the commission percentage
      $percentage = (int)(\App\Options::getLatestCommission())->value;
      // dd($dueSavings);
      $details = \App\Options::getLatestCommissionBankDetails();
      // app logo
      $logo = \App\Setting::findName(['logo']);
      $blanceDue = \App\CollectionCommission::calculateUnsettledCommission();
      return view('branch.invoice', compact('details', 'dueSavings', 'percentage', 'blanceDue', 'user', 'logo'));
    }
}

resources/views/branch/payment_status.blade.php
@extends('layouts.app')

@section('title') Payment Status @endsection

@section('link')
@endsection

@section('content')
<!--CONTENT CONTAINER-->
<!--===================================================-->
<div id="content-container">
  <div id="page-head">

      <!--Page Title-->
      <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
      <div id="page-title">
          <h1 class="page-header text-overflow">Payment Status</h1>
      </div>
      <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
      <!--End page title-->

      <!--Breadcrumb-->
      <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
      <ol class="breadcrumb">
        <li>
            <i class="fa fa-home"></i><a href="{{route('dashboard')}}"> Dashboard</a>
        </li>
          <li class="active">Status</li>
      </ol>
      <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
      <!--End breadcrumb-->

  </div>


  <!--Page content-->
  <!--===================================================-->
  <div id="page-content">
    <div class="panel rounded-top text-center">
      <!-- <div class="panel-heading card">
        <h1 class="display-1 text-center"><i class="fa fa-{{session('status') ? 'mark' : 'close'}}"></i> {{session('message')}}ggfg</h1>
      </div> -->
      <div class="panel-body">
        <div class="text-xs-center bg-{{session('status') ? 'success' : 'danger'}} card border border-light col-md-6 col-md-offset-2">
          <div class="card-block">
            <h1 class="display-3 mb-0">Thank You!</h1>
            <h1 class="display-1 text-center"><i class="fa fa-{{session('status') ? 'mark' : 'close'}}"></i> {{session('message')}}</h1>
            @if (session('status'))
            <p class="lead"><strong>Please check your email</strong> for payment receipt.</p>
            <hr>
            @endif
            <p>
              Having trouble? <a href="">Contact us</a>
            </p>
            <p class="lead  mb-0">
              <a class="btn btn-primary btn-sm" href="{{Route('dashboard')}}" role="button">Continue to homepage</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/branch/register.blade.php
@extends('layouts.app')

@section('title') Branch Registration @endsection

@section('content')
<!--CONTENT CONTAINER-->
<!--===================================================-->
<div id="content-container">
	<div id="page-head">
		<!--Page Title-->
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<div id="page-title">
			<h1 class="page-header text-overflow">Branch Registration</h1>
		</div>
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<!--End page title-->
		<!--Breadcrumb-->
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<ol class="breadcrumb">
			<li>
					<i class="fa fa-home"></i><a href="{{route('dashboard')}}"> Dashboard</a>
			</li>
			<li class="active">Registration</li>
		</ol>
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<!--End breadcrumb-->
	</div>
	<!--Page content-->
	<!--===================================================-->
	<div id="page-content">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<div class="panel" style="background-color: #e8ddd3;">
					<div class="panel-heading">
						<h2 class="panel-title text-center">Register Branch</h2>
					</div>
					@include('layouts.error')

					<!-- BASIC FORM ELEMENTS -->
					<!--===================================================-->
					<div class="cls-content">
		        <div class="cls-content-lg panel">
		            <div class="panel-body">
		                <div class="mar-ver pad-btm">
		                    <h1 class="h3">Create a New Branch Account</h1>
		                    <p>Set up account.</p>
		                </div>
										@if (isset($_GET['s']))
										<div class="alert alert-success" role="alert">
											<span class="text-danger">
													<strong>New Branch added Successfully</strong>
											</span>
										</div>
										@endif
		                <form id="branch-form" action="{{route('branch.register')}}" method="POST">
		                @csrf
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input id="branchname" placeholder="Branch Name" type="text" class="form-control{{ $errors->has('branchname') ? ' is-invalid' : '' }}" name="branchname" value="{{ old('branchname') }}" required autofocus>

                                @if ($errors->has('branchname'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('branchname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input id="branchcode" placeholder="Branch Code" type="text" class="form-control{{ $errors->has('branchcode') ? ' is-invalid' : '' }}" name="branchcode" value="{{ old('branchcode') }}" required>

                                @if ($errors->has('branchcode'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('branchcode') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <input id="email" type="email" placeholder="Email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <input id="password" type="password" placeholder="Password " class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input id="password-confirm" type="password" placeholder="Password Confimation"  class="form-control" name="password_confirmation" required>

                            </div>
                        </div>
                    </div>
                    <div class="row">
											<div class="col-sm-12">
													<div class="form-group">
															<textarea type="text" class="form-control" placeholder="Branch Address" name="address"></textarea>
															@if ($errors->has('address'))
																	<span class="invalid-feedback">
																			<strong>{{ $errors->first('address') }}</strong>
																	</span>
															@endif
													</div>
											</div>
											<div class="col-sm-3">
													<div class="form-group">
															<input id="city" type="city" placeholder="City" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city') }}" required>

															@if ($errors->has('city'))
																	<span class="invalid-feedback">
																			<strong>{{ $errors->first('city') }}</strong>
																	</span>
															@endif
													</div>
											</div>
											<div class="col-sm-3">
													<div class="form-group">
															<input id="state" type="state" placeholder="State" class="form-control{{ $errors->has('state') ? ' is-invalid' : '' }}" name="state" value="{{ old('state') }}" required>

															@if ($errors->has('state'))
																	<span class="invalid-feedback">
																			<strong>{{ $errors->first('state') }}</strong>
																	</span>
															@endif
													</div>
											</div>
											<div class="col-sm-3">
													<div class="form-group">
															<!--input id="country" type="country" placeholder="Country" class="form-control{{ $errors->has('country') ? ' is-invalid' : '' }}" name="country" value="{{ old('country') }}" required-->
															<select  id="country"class="form-control {{ $errors->has('country') ? ' is-invalid' : '' }}" name="country" required>
																<option value="" selected disabled>Country</option>
                             		<!-- <option value="158">Nigeria</option> -->
                              </select>
															@if ($errors->has('country'))
																	<span class="invalid-feedback">
																			<strong>{{ $errors->first('country') }}</strong>
																	</span>
															@endif
													</div>
											</div>
											<div class="col-sm-3">
													<div class="form-group">
															<!--input id="country" type="country" placeholder="Country" class="form-control{{ $errors->has('country') ? ' is-invalid' : '' }}" name="country" value="{{ old('country') }}" required-->
															<select class="form-control {{ $errors->has('currency') ? ' is-invalid' : '' }}" name="currency" required placeholder="Enter Branch Currency">
																 <option value="" selected disabled>Currency</option>
																 @foreach($currencies as $currency)
																 @if($currency->currency_symbol)
																 <option value="{{$currency->currency_symbol}}" {{$currency->name == 'Nigeria' ? 'selected' : '' }}>{{$currency->currency_name}} - {{$currency->currency_symbol}}</option>
																 @endif
																 @endforeach
															 </select>
															@if ($errors->has('currency'))
																	<span class="invalid-feedback">
																			<strong>{{ $errors->first('currency') }}</strong>
																	</span>
															@endif
													</div>
											</div>
                    </div>
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Register</button>
                </form>
            </div>
        </div>
    </div>
    <!--===================================================-->
				</div>
			</div>
		</div>


	</div>
	<!--===================================================-->
	<!--End page content-->

</div>
<!--===================================================-->
<!--END CONTENT CONTAINER-->

@endsection

@section('js')
<script>
$(document).ready(() => {
	select = $('#country')
	getCountries().then((res)=>{ $(select).append(options(res))})
})
async function getCountries(){
  res = await $.ajax({url: "{{route('option.countries')}}"})
	return res
}

function options(countries){
	opt = ''
	countries.forEach((v) => {
		opt += `<option ${(v.name === 'Nigeria') ? 'selected' : ''} value="${v.name}">${v.name}</option>`
	})
	return opt
}
</script>
@endsection

resources/views/branch/test.blade.php
@foreach($all as $row)
  <p>{{$row->HOFNAME}}</p>
  <p>{{$row->HOLNAME}}</p>
  <p>{{$row->HOCITY}}</p>
  <p>{{$row->HOCOUNTRY}}</p>
  <p>{{$row->HOADDRESS}}</p>
@endforeach